<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>5a764a5b-e092-4003-ae3e-b61090fff3b8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\DATA\Level\" />
    <Folder Include="wwwroot\DATA\Depot\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NL">
      <HintPath>..\..\..\___NL\NL.dll</HintPath>
    </Reference>
    <Reference Include="NLWeb">
      <HintPath>..\..\..\___NL\NLWeb.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
